### ISSUE TITLE
lua5.2: shiro-fextr.lua:54: module '/home/___/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-dae-16k.lua' not found:

### ISSUE THREAD

**Issue by caseybasichis** [Sleepwalking/SHIRO#2]
Hi,

Building on linux, I'm encountering a problem running SHIRO.

I've tried with adding the .lua to the extrator as well but I get the same error.

lua5.2 shiro-fextr.lua ~/Downloads/UTAU/Resonance_Harmony_Arpasing_English/Base_B3/index.csv -d ~/Downloads/UTAU/Resonance_Harmony_Arpasing_English/Base_B3/ -x ~/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k -r 16000
lua5.2: shiro-fextr.lua:54: module '/home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k' not found:
        no field package.preload['/home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k']
        no file '/usr/local/share/lua/5.2//home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k.lua'
        no file '/usr/local/share/lua/5.2//home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k/init.lua'
        no file '/usr/local/lib/lua/5.2//home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k.lua'
        no file '/usr/local/lib/lua/5.2//home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k/init.lua'
        no file '/usr/share/lua/5.2//home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k.lua'
        no file '/usr/share/lua/5.2//home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k/init.lua'
        no file './/home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k.lua'
        no file '/usr/local/lib/lua/5.2//home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.2//home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k.so'
        no file '/usr/lib/lua/5.2//home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k.so'
        no file '/usr/local/lib/lua/5.2/loadall.so'
        no file './/home/myname/Prog/audio/SHIRO/extractors/extractor-xxcc-mfcc12-da-16k.so'
stack traceback:
        [C]: in function 'require'
        shiro-fextr.lua:54: in main chunk
        [C]: in ?

**Comment by caseybasichis** [comment]
Got it working! (or at least the first step)

The -d path had to be in quotes and also didn't work with the ~/ home alias

**Comment by Sleepwalking** [comment]
Hello Casey Basichis,

The Lua based tools only accept relative paths as of now. I'm looking into how to detect whether a path is absolute or relative, without adding a bunch of largely irrelevant dependencies.

**Comment by caseybasichis** [comment]
Hi Kanru,

I was stuck on the new tutoiral until I realized I needed the step on the github tutorial "Create model and (Arpabet) phoneme definitions for American English"

I'm getting an error in the aligned.json

Error: phoneme iy
 is not defined in the phone map.

But it is defined in both the arpabet-phoneset.csv and phonemap.json

**Comment by Sleepwalking** [comment]
@caseybasichis could you show me the commands from the first step?

Does SHIRO work with CMU_ARCTIC on your machine?

**Comment by Sleepwalking** [comment]
The path parsing issue in `shiro-fextr.lua` has been fixed in commit 1ea9391fc676cf613534304bd1ff67e8947056eb.
