### ISSUE TITLE
content of index.csv

### ISSUE THREAD

**Issue by prashantmaheshwari94** [Sleepwalking/SHIRO#3]
Hi,
lua shiro-fextr.lua index.csv   -d "../cmu_us_bdl_arctic/orig/"   -x ./extractors/extractor-xxcc-mfcc12-da-16k -r 16000
Can you tell what is the content of index.csv file which is one of the input argument for speech-phoneme alignment.
Also what path should be provided for -d argument

Thanks

**Comment by Sleepwalking** [comment]
Hello,

Please take a look at [examples/index-cmu-arctic-slt.csv](https://github.com/Sleepwalking/SHIRO/blob/master/examples/index-cmu-arctic-slt.csv).
Side note: if I remember correctly, BDL has a few sentences missing compared to SLT.

`-d` points to the directory where the wav files are placed. The first column in `index.csv` will be appended to the directory path with `.wav` extension in the end.
