### ISSUE TITLE
when load the model, Null point always returned.

### ISSUE THREAD

**Issue by seongyeop-jeong-poey** [Sleepwalking/SHIRO#6]
hello, first thanks for the nice framework.

the extraction of mfcc and first, second-order delta feature works well. 
After that, when I load the model(.hsmm) 

> the Error: failed to load model from blah blah

 .. error is occurred.

Some model file(empty.hsmm) doesn't occur above error.
And i made some **test.txt or text.hsmm** file and change the from path to test file to check the fopen function in hsmm = load_model(optarg) in shiro-rest.c whether it works well. But it also got an error! 

fopen return success by checking 'perror', it returns 'Success'. the custom c file i made also can read any .hsmm and test.txt.
but it doesn't works only in your shiro-rest.c code.

I can't resolve this situation, how can i resolve this problem?

![image](https://user-images.githubusercontent.com/37603367/148202729-068b7ce5-0389-4444-b008-d2dd6bae4697.png)

**Comment by Sleepwalking** [comment]
Hello. How did you create `flat.hsmm`? Would you share the file for an inspection?

**Comment by seongyeop-jeong-poey** [comment]
> Hello. How did you create `flat.hsmm`? Would you share the file for an inspection?

I just follow up your kind instruction.
like this
`lua shiro-mkseg.lua index.csv \
  -m phonemap.json \
  -d "../cmu_us_bdl_arctic/orig/" \
  -e .param -n 36 -L sil -R sil > unaligned-segmentation.json
./shiro-init \
  -m empty.hsmm \
  -s unaligned-segmentation.json \
  -FT > flat.hsmm`

All of your instruction doesn't seem to got error.
I just download the CMU Arctic speech database and change the some instruction path. for example 'cmu_us_bdl_arctic/orig/' to 'cmu_us_bdl_arctic/wav/'(i can't find the orig path in dataset. i guess the wav path directory from orig to wav)

At first time, i try to inference the below code(I use ./examples/cmu-arctic-all-speakers.hsmm model instead trained-model.hsmm). but it also can't load the model. so i decide to train the another model through your training instructions.
`./shiro-align \
  -m trained-model.hsmm \
  -s unaligned.json \
  -g > initial-alignment.json
./shiro-align \
  -m trained-model.hsmm \
  -s initial-alignment.json \
  -p 10 -d 50 > refined-alignment.json`

**Comment by seongyeop-jeong-poey** [comment]
> Hello. How did you create `flat.hsmm`? Would you share the file for an inspection?

Sorry for my mistake to run the your instrunment.

I replace the path from "/cmu_us_bdl_arctic/orig/" to "/cmu_us_bdl_arctic/wav/".
But, the right way to modify is changing to "/cmu_us_bdl_arctic/wav"(please remove '/').
Finally, like the below figure, the training is successful!

All of top to end are work very well.
nice code!
Thanks a lot!

![image](https://user-images.githubusercontent.com/37603367/148332588-99bc72dc-36ce-4567-91cc-ffb0990dbe6d.png)
